name: Generate and upload Kaspi XML

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account credentials
        run: |
          echo '${{ secrets.GDRIVE_CREDENTIALS }}' > credentials.json

      - name: Run generator and upload to Drive
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python cloud_run.py

      - name: Show upload result
        if: always()
        run: |
          if [ -f kaspi_upload_result.json ]; then cat kaspi_upload_result.json; else echo 'No result file'; fi
